### ISSUE TITLE
search interface for canonical entity table

### ISSUE THREAD

**Issue by jernsthausen** [datamade/dedupe-api#118] opened 2015-03-11 16:13 UTC
It'd be very helpful, both for making dedupe accessible to non-experts and for helping people see the power of dedupe, if there were a search feature built on top of records linked together in our master table of entities and associated records.

Best part: deduping search against deduped database.

**Comment by derekeder** [comment] 2015-03-16 20:43
duplicate of #30

**Closed by derekeder** 2015-03-16 20:43 UTC
